---
# Source: prometheus-operator/charts/prometheus-node-exporter/templates/psp-clusterrole.yaml

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:     
    app: prometheus-node-exporter
    heritage: Tiller
    release: prom-operator
    chart: prometheus-node-exporter-1.7.0
    jobLabel: node-exporter
    
  name: psp-prom-operator-prometheus-node-exporter
rules:
- apiGroups: ['extensions']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - prom-operator-prometheus-node-exporter
