---
# Source: prometheus-operator/templates/exporters/kube-api-server/servicemonitor.yaml

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prom-operator-prometheus-o-apiserver
  namespace: monitoring
  labels:
    app: prometheus-operator-apiserver
    
    chart: prometheus-operator-6.20.3
    release: "prom-operator"
    heritage: "Tiller"
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    port: https
    scheme: https
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      serverName: kubernetes
      insecureSkipVerify: false
  jobLabel: component
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      component: apiserver
      provider: kubernetes
    
