---
# Source: prometheus-operator/charts/grafana/templates/secret.yaml

apiVersion: v1
kind: Secret
metadata:
  name: prom-operator-grafana
  namespace: monitoring
  labels:
    app: grafana
    chart: grafana-3.12.1
    release: prom-operator
    heritage: Tiller
type: Opaque
data:
  admin-user: "YWRtaW4="
  admin-password: "YWRtaW4="
  ldap-toml: ""
