---
# Source: prometheus-operator/charts/grafana/templates/serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: grafana
    chart: grafana-3.12.1
    heritage: Tiller
    release: prometheus
  name: prometheus-grafana
  namespace: monitoring
