---
# Source: prometheus-operator/templates/prometheus-operator/deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: prom-operator-prometheus-o-operator
  namespace: monitoring
  labels:
    app: prometheus-operator-operator
    
    chart: prometheus-operator-6.20.3
    release: "prom-operator"
    heritage: "Tiller"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-operator-operator
      release: "prom-operator"
  template:
    metadata:
      labels:
        app: prometheus-operator-operator
        
        chart: prometheus-operator-6.20.3
        release: "prom-operator"
        heritage: "Tiller"
    spec:
      containers:
        - name: prometheus-operator
          image: "quay.io/coreos/prometheus-operator:v0.32.0"
          imagePullPolicy: "IfNotPresent"
          args:
            - --kubelet-service=kube-system/prom-operator-prometheus-o-kubelet
            - --logtostderr=true
            - --crd-apigroup=monitoring.coreos.com
            - --localhost=127.0.0.1
            - --prometheus-config-reloader=quay.io/coreos/prometheus-config-reloader:v0.32.0
            - --config-reloader-image=quay.io/coreos/configmap-reload:v0.0.1
            - --config-reloader-cpu=100m
            - --config-reloader-memory=25Mi
          ports:
            - containerPort: 8080
              name: http
          resources:
            {}
            
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        
      serviceAccountName: prom-operator-prometheus-o-operator
