---
# Source: prometheus-operator/templates/prometheus-operator/serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  name: prom-operator-prometheus-o-operator
  namespace: monitoring
  labels:
    app: prometheus-operator-operator
    
    chart: prometheus-operator-6.20.3
    release: "prom-operator"
    heritage: "Tiller"
imagePullSecrets:
  []
  
