---
# Source: prometheus-operator/templates/prometheus-operator/admission-webhooks/mutatingWebhookConfiguration.yaml

apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name:  prometheus-prometheus-oper-admission
  namespace: monitoring
  labels:
    app: prometheus-operator-admission    
    chart: prometheus-operator-6.20.3
    release: "prometheus"
    heritage: "Tiller"
webhooks:
  - name: prometheusrulemutate.monitoring.coreos.com
    failurePolicy: Fail
    rules:
      - apiGroups:
          - monitoring.coreos.com
        apiVersions:
          - "*"
        resources:
          - prometheusrules
        operations:
          - CREATE
          - UPDATE
    clientConfig:
      service:
        namespace: monitoring
        name: prometheus-prometheus-oper-operator
        path: /admission-prometheusrules/mutate
