{
 "title": "PKS Control Plane",
 "description": "This dashboard is designed for monitoring the PKS control plane using Reliability View for PCF. ",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Healthy Master Nodes",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(system_healthy{exported_job=\"master\"})\n"
    }
   ]
  },
  {
   "title": "Healthy Jobs",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "(system_healthy)\n\n", "legendFormat": "{{exported_job}} {{instance}}" },
    {}
   ]
  },
  {
   "title": "Total Healthy Workers",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(system_healthy{exported_job=\"worker\"})"
    },
    {}
   ]
  },
  {
   "title": "Master Node Memory Consumption",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "system_mem_percent{exported_job=\"master\"}"
    },
    {},
    {}
   ]
  },
  {
   "title": "Master Node Memory Availability",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_disk_ephemeral_percent{exported_job=\"master\"}",
     "legendFormat": "{{instance}}"
    },
    {}
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "PKS API Memory and CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_cpu_user{exported_job=\"pivotal-container-service\"}",
     "legendFormat": "CPU %"
    },
    {
     "expr": "system_mem_percent{exported_job=\"pivotal-container-service\"}\n",
     "legendFormat": "Memory %"
    }
   ]
  }
 ]
}