resources:
- name: prometheus-deployment
  type: git
  source:
    uri: ((repo.uri))
    branch: ((repo.branch))
    private_key: ((repo.private_key))

jobs:
- name: install
  serial_groups: [install]
  plan:
  - get: repo
    resource: prometheus-deployment
    trigger: true

  - task: pks-login
    file: repo/ci/tasks/pks-login/task.yml
    params:
      PKS_API_URL: ((pks_api_url))
      PKS_USER: ((pks_user))
      PKS_PASSWORD: ((pks_password))
      K8S_CLUSTER_NAME: ((k8s_cluster_name))

  - task: lint
    file: repo/ci/tasks/helm-lint/task.yml
    params:
      RELEASE: ((release))

  - task: install-operator
    file: repo/ci/tasks/install-operator/task.yml
    params:
      OM_TARGET: ((om_target))
      OM_USERNAME: ((om_username))
      OM_PASSWORD: ((om_password))
      OM_SKIP_SSL_VALIDATION: ((om_skip_ssl_validation))
      BOSH_UAA_CLIENT_ID: ((bosh_uaa_client_id))
      BOSH_UAA_CLIENT_SECRET: ((bosh_uaa_client_secret))
      PKS_API_HOSTNAME: ((pks_api_hostname))
      PKS_API_MONITOR_SECRET: ((pks_api_monitor_secret))
      FOUNDATION: ((foundation))
      NAMESPACE: ((namespace))
      RELEASE: ((release))
      VERSION: ((version))

- name: test
  serial_groups: [install]
  plan:
  - get: repo
    resource: prometheus-deployment
    trigger: true
    passed: [install]

  - task: pks-login
    file: repo/ci/tasks/pks-login/task.yml
    params:
      PKS_API_URL: ((pks_api_url))
      PKS_USER: ((pks_user))
      PKS_PASSWORD: ((pks_password))
      K8S_CLUSTER_NAME: ((k8s_cluster_name))

  - task: test
    file: repo/ci/tasks/helm-test/task.yml
    params:
      RELEASE: ((release))
      NAMESPACE: ((namespace))

- name: uninstall
  serial_groups: [install]
  plan:
  - get: repo
    resource: prometheus-deployment

  - task: pks-login
    file: repo/ci/tasks/pks-login/task.yml
    params:
      PKS_API_URL: ((pks_api_url))
      PKS_USER: ((pks_user))
      PKS_PASSWORD: ((pks_password))
      K8S_CLUSTER_NAME: ((k8s_cluster_name))

  - task: uninstall-operator
    file: repo/ci/tasks/uninstall-operator/task.yml
    params:
      RELEASE: ((release))
      NAMESPACE: ((namespace))
