---
# Source: prometheus-operator/templates/exporters/kube-etcd/servicemonitor.yaml

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-prometheus-oper-kube-etcd
  namespace: monitoring
  labels:
    app: prometheus-operator-kube-etcd
    
    chart: prometheus-operator-6.20.3
    release: "prometheus"
    heritage: "Tiller"
spec:
  jobLabel: jobLabel
  selector:
    matchLabels:
      app: prometheus-operator-kube-etcd
      release: "prometheus"
  namespaceSelector:
    matchNames:
      - "kube-system"
  endpoints:
  - port: http-metrics
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
